---
- name: Install virtualenv package
  apt:
    name: python-virtualenv
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_time }}"

- name: Create virtualenv
  command: virtualenv --python={{ venv_python }} {{ venv }}
  args:
    creates: "{{ venv }}"

- name: Set ownership of virtualenv directory
  file:
    path: "{{ venv }}"
    state: directory
    owner: "{{ venv_owner | default(omit) }}"
    group: "{{ venv_group | default(omit) }}"
    recurse: yes
